[package]
name = "musplay"
version = "0.1.0"
authors = ["Jonas Minnberg <sasq64@gmail.com>"]
edition = "2018"
build="build.rs"

[dependencies]
coreaudio-rs = "0.9.1"

[build-dependencies]
cmake = "0.1.31"
